---

- name: "Debian: Add timescaledb.com repository GPG key"
  ansible.builtin.apt_key:
    url: "{{ timescaledb__gpg_url }}"

- name: "Debian: Configure timescaledb.com apt repository"
  ansible.builtin.apt_repository:
    repo: "{{ timescaledb__apt_repo }}"
    state: present
    update_cache: yes

- name: "Debian: Install timescaledb package"
  ansible.builtin.apt:
    name: "timescaledb-{{ timescaledb__version }}-postgresql-{{ postgresql__version }}"
    state: present
  notify:
    - Restart postgresql
