---

- name: "Checking TimescaleDB supported version"
  ansible.builtin.fail:
    msg: "Not a supported TimeScaleDB version {{ timescaledb__version }}"
  when: ( timescaledb__version < 2 ) or ( timescaledb__version > 2 )

- name: "Install Debian based OS"
  ansible.builtin.include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
